# Generated by Django 4.2.1 on 2023-05-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Button",
            fields=[
                ("button_id", models.AutoField(primary_key=True, serialize=False)),
                ("button_name", models.CharField(max_length=255)),
                ("button_icon", models.CharField(max_length=255)),
                ("button_function", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "arui_button",
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                ("sku_id", models.AutoField(primary_key=True, serialize=False)),
                ("sku_name", models.CharField(max_length=255)),
                ("sku_image", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "arui_sku",
            },
        ),
        migrations.CreateModel(
            name="SKUBtn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "button",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feature_api.button",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feature_api.sku",
                    ),
                ),
            ],
            options={
                "db_table": "arui_sku_btn",
                "unique_together": {("sku", "button")},
            },
        ),
    ]
