# Generated by Django 4.2.1 on 2023-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="button",
            name="button_icon",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
