# Generated by Django 4.2.1 on 2023-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feature_api", "0002_alter_button_button_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="sku_image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
